export default {
    account: 'Login to Account',
    loginpage: 'Please enter your email and password to continue',
    signin: 'Sign In',
    email: 'Email Address',
    password: 'Password',
    confirm: 'Confirm Your Email',
    name: 'Your Name',
    login: 'Log In',
    signup: 'Create Account',
    signuppage:'Please enter personal information to continue',
    forgotpassword: 'Forgot Password?',
    notmember: 'Do Not have an account?',
    register: 'Register',
    back: 'Back To Login',
    forgot: 'Forgot Password?',
    reset:'Forgot Password',
    dashboard: 'Dashboard',
    home: 'Home',
    about: 'About',
    service: 'Service',
    logout: 'Logout',
    filepath:'http://api.kartzoapp.com/',
    mainUrl:'http://api.kartzoapp.com/api/',
    apiUrl: 'http://api.kartzoapp.com/v1/',
    headers: {
        Authorization: 'Bearer ' + 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoidXNlciBhYmMiLCJuYmYiOjE1OTU1NjUxNDMsImV4cCI6MTU5NTU4Njc0MywiaWF0IjoxNTk1NTY1MTQzfQ.KfSFaBXToiMLq4ULJUBmurIaNUrmZx181xqKOAD7il1Xr380mHx1DhpfV0OnqYuq-_IDhH3WzNKWIX31TnpjSQ',
        'Access-Control-Allow-Origin': true
    },
    firstname:'Firstname',
    lastname:'Lastname',
    changepassword: 'Change Password',
    dashboardTitle: 'Dashboard',
    userTitle: 'User Management',
    addUserTitle: 'Add User',
    updateUserTitle: 'Update User',
    viewUserTitle: 'View User',
    userRoleTitle: 'Role Management',
    viewUserRoleTitle: 'View Role',
    adduserRoleTitle: 'Add Role',
    updateRoleTitle: 'Update Role',
    rolePrivilegesTitle: 'Role Privileges',
    countryTitle: 'Country Management',
    stateTitle:'State Management',
    cityTitle:'City Management',
    addCountryTitle:'Add Country',
    addStateTitle:'Add State',
    addCityTitle:'Add City',
    viewCityTitle:'View City',
    viewStateTitle:'View State',
    viewCountryTitle:'View Country',
    categoryTitle:'Category Management',
    addCategoryTitle:'Add Category',
    updateCategoryTitle:'Update Category',
    viewCategoryTitle:'View Category',
    subcategoryTitle:'Sub Category Management',
    addSubCategoryTitle:'Add SubCategory',
    viewSubCategoryTitle:'View SubCategory',
    profileTitle:'Profile',
    loginTitle:'Login',
    signupTitle:'Signup',
    couponManagement:'Coupon Management',
    merchantManagement:'Merchant Management',
    merchantBusinessManagement:'Merchant Business Management',
    merchantReviewManagement:'Merchant Review Management',
    viewProductManagement:'View Product',
    listProduct:'List Product',
    addProduct:'Add Product',
    imageProduct:'Image Product',
    listImageProduct:'List Image Product',
    inventoryProduct:'Add Inventory Product',
    viewImageProduct:'View Image Product',
    reviewProduct:'Review Product',
    addonProduct:'AddOn Product',
    delivery:'Delivery Management',
    addDelivery:'Add Delivery',
    viewDelivery:'View Delivery',
    listMerchantReview:'Merchant Review',
    listInventoryProduct:'Inventory Management',
    viewInventoryProduct:'View Inventory',
    viewProductReview:'View Product Review',
    ViewMerchantReview:'View Merchant Review',
    listOrderManagement:'Order Management',
    viewOrderManagement:'View Order',
    addCartOrder:'Order Cart Management',
    addOrder:'Add Order',
    listCartManagement: 'Cart Management',
    viewCartManagement:'View Order Cart',
    addCustomerTitle:'Add Customer',
    viewCustomerTitle:'View Customer',
    listCustomer:'Customer Management',
    addAddress:'Add Address',
    listAddress:'Address Management',
    viewAddress:'View Address',
    listCard:'Card Management',
    addCard:'Add Card',
    viewCard:'View Card',
    userTableColumn: [
        { name: 'firstName', title: "First Name", type: "text" },
        { name: "lastName", title: "Last Name", type: "text" },
        { name: "email", title: "E-mail", type: "text" },
        { name: "role", title: "Role", type: "text" }
        // { name: "status", title: "Status", type: "text" },
        // { name: "role", title: "Role", type: "text" }
      ],
    // userTableColumn: [
    //     'First Name', 'Last Name','E-mail','Role','Status','Action'
    // ],
    roleTableColumn: [
        'Role Name','Status','Action'
    ],
    // roleTableColumn: [
    //     'Role Name','Status','Action'
    // ],

}